### ISSUE TITLE
Registration Email -- Confirmation URL is incorrect

### ISSUE THREAD

**Issue by JordanMalan** [SunSpecOrangeButton/ahj-registry#24]
Hi, I've been curious in this project since I first saw it so I decided to sign up, however the link provided in the email is wrong, here's what I received:
sunspec.org/api/v1/activate/xxx/yyy-yyyyyyyyyyyyyyyyyyyy/

which led to a 404, as a developer I decided to try:
https://ahjregistry.sunspec.org/api/v1/activate/xxx/yyy-yyyyyyyyyyyyyyyyyyyy/

which worked.
Hopefully this helps.
P.S. it looks like throughout the app, https:// is required, regular http:// should redirect instead of erroring out.

**Comment by JordanMalan** [comment]
My guess:
update EMAIL_LINK_DOMAIN environment variable in production
and update http:// to https:// in  ~ahj-registry/server/core/templates/acc_active_email.html

**Comment by btansy** [comment]
@JordanMalan you were right on both counts. Master branch has been updated and the changes are currently live on production. Thanks for the help!
